    - hosts: all
      tasks:
      # Install ASDF
      - name: Git clone ASDF
        become_user: vagrant
        ansible.builtin.git:
          repo: 'https://github.com/asdf-vm/asdf.git'
          dest: "/home/vagrant/.asdf"
          version: "v0.11.3"

      - name: Add ASDF to .bashrc
        become_user: vagrant
        ansible.builtin.lineinfile:
          path: /home/vagrant/.bashrc
          line: '. /home/vagrant/.asdf/asdf.sh'
          insertafter: EOF

      - name: Add ASDF bash-completion to .bashrc
        become_user: vagrant
        ansible.builtin.lineinfile:
          path: /home/vagrant/.bashrc
          line: '. /home/vagrant/.asdf/completions/asdf.bash'
          insertafter: EOF

      - name: Install ASDF Java plugin
        become_user: vagrant
        ansible.builtin.shell: |
          source /home/vagrant/.bashrc
          /home/vagrant/.asdf/bin/asdf plugin add java
        args:
          executable: /bin/bash

      - name: Install Java with ASDF and set it as global default
        become_user: vagrant
        ansible.builtin.shell: |
          source /home/vagrant/.bashrc
          /home/vagrant/.asdf/bin/asdf install java temurin-17.0.8+7
          /home/vagrant/.asdf/bin/asdf global java temurin-17.0.8+7
        args:
          executable: /bin/bash
